// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: aadharData.proto

package protoservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AadharDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	PhoneNumber  string `protobuf:"bytes,3,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	DateOfBirth  string `protobuf:"bytes,4,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	AddressLine1 string `protobuf:"bytes,5,opt,name=AddressLine1,proto3" json:"AddressLine1,omitempty"`
	AddressLine2 string `protobuf:"bytes,6,opt,name=AddressLine2,proto3" json:"AddressLine2,omitempty"`
	Pincode      string `protobuf:"bytes,7,opt,name=Pincode,proto3" json:"Pincode,omitempty"`
	City         string `protobuf:"bytes,8,opt,name=City,proto3" json:"City,omitempty"`
	State        string `protobuf:"bytes,9,opt,name=State,proto3" json:"State,omitempty"`
	Image        string `protobuf:"bytes,10,opt,name=Image,proto3" json:"Image,omitempty"`
	Signature    string `protobuf:"bytes,11,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *AadharDetails) Reset() {
	*x = AadharDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aadharData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AadharDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadharDetails) ProtoMessage() {}

func (x *AadharDetails) ProtoReflect() protoreflect.Message {
	mi := &file_aadharData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadharDetails.ProtoReflect.Descriptor instead.
func (*AadharDetails) Descriptor() ([]byte, []int) {
	return file_aadharData_proto_rawDescGZIP(), []int{0}
}

func (x *AadharDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AadharDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AadharDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AadharDetails) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *AadharDetails) GetAddressLine1() string {
	if x != nil {
		return x.AddressLine1
	}
	return ""
}

func (x *AadharDetails) GetAddressLine2() string {
	if x != nil {
		return x.AddressLine2
	}
	return ""
}

func (x *AadharDetails) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *AadharDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AadharDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AadharDetails) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AadharDetails) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_aadharData_proto protoreflect.FileDescriptor

var file_aadharData_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x61, 0x64, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xb7, 0x02, 0x0a, 0x0d, 0x41, 0x61, 0x64,
	0x68, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72,
	0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6e,
	0x65, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x6e, 0x65, 0x31, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x6e, 0x65, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aadharData_proto_rawDescOnce sync.Once
	file_aadharData_proto_rawDescData = file_aadharData_proto_rawDesc
)

func file_aadharData_proto_rawDescGZIP() []byte {
	file_aadharData_proto_rawDescOnce.Do(func() {
		file_aadharData_proto_rawDescData = protoimpl.X.CompressGZIP(file_aadharData_proto_rawDescData)
	})
	return file_aadharData_proto_rawDescData
}

var file_aadharData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aadharData_proto_goTypes = []interface{}{
	(*AadharDetails)(nil), // 0: handler.protoservice.AadharDetails
}
var file_aadharData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aadharData_proto_init() }
func file_aadharData_proto_init() {
	if File_aadharData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aadharData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AadharDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aadharData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aadharData_proto_goTypes,
		DependencyIndexes: file_aadharData_proto_depIdxs,
		MessageInfos:      file_aadharData_proto_msgTypes,
	}.Build()
	File_aadharData_proto = out.File
	file_aadharData_proto_rawDesc = nil
	file_aadharData_proto_goTypes = nil
	file_aadharData_proto_depIdxs = nil
}
